# Complete infra creation for selenium chrome/firefox and owasp security testing

version: '3'

services:
  firefox:
    image: selenium/node-firefox:4.0.0-alpha6-20200609
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  chrome:
    image: selenium/node-chrome:4.0.0-alpha6-20200609
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  hub:
    image: selenium/hub:4.0.0-alpha6-20200609
    ports:
      - "4444:4444"

  zaproxy:
    image: owasp/zap2docker-stable:latest
    command: [
      #"zap.sh",
      "zap-x.sh",
      #"zap-webswing.sh",
      "-daemon",
      "-host", "0.0.0.0", "-port", "8082",
      "-config", "api.disablekey=true",
      "-config", "api.addrs.addr.name=.*",
      "-config", "api.addrs.addr.regex=true",
      "-config", "api.key=d025okl6n7blpkrr0iee6c7hsi",
      #"-addoninstall FOOXYZ",
      "-addonupdate"
    ]
    ports:
      - "127.0.0.1:8082:8082"

  rabbitmq:
    image: rabbitmq:3.8.7-management
    hostname: my-rabbit
    volumes:
      - ./input/rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
      - ./input/rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
      - ./rabbitmq/logs:/var/log/rabbitmq/log
    ports:
      - 5672:5672
      - 15672:15672